name: GitHub Pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Deploy

    environment:
      name: github-pages
      url: ${{ steps.pages.outputs.page_url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Zola
        run: sudo snap install zola --edge
      - name: Setup WeasyPrint
        run: pip install weasyprint
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3
      - name: Setup ExifTool
        run: sudo apt-get install libimage-exiftool-perl -y
      - name: Build [Zola]
        run: zola build
      - name: Build [WeasyPrint]
        run: |
          mkdir docs
          weasyprint public/index.html docs/cv.pdf
      - name: Update PDF MetaData
        run: |
          exiftool \
            -Title="Curriculum Vitae" \
            -Author="Stefan Kühnel" \
            -Copyright="© $(date +%Y) Stefan Kühnel. Alle Rechte vorbehalten." \
            -Subject="Curriculum Vitae" \
            -Keywords="Curriculum Vitae, CV" \
            -Software="$(weasyprint --version)" \
            -Producer="$(weasyprint --version)" \
            -Creator="$(weasyprint --version)" \
            docs/cv.pdf
      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: pages
        uses: actions/deploy-pages@v1
